### ISSUE TITLE
What versions of Webpack does the plugin support?

### ISSUE THREAD

**Issue by ghost** [skipjack/directory-tree-webpack-plugin#1]
Hi
With webpack version 4.15.1 I got a building error:

```
D:\PATH_TO_MY_PROJECT\node_modules\copy-webpack-plugin\dist\index.js:186
                    trackedDirs.push(context);
                                ^

TypeError: trackedDirs.push is not a function
    at D:\PATH_TO_MY_PROJECT\node_modules\copy-webpack-plugin\dist\index.js:186:33
    at arrayEach (D:\PATH_TO_MY_PROJECT\node_modules\lodash\lodash.js:516:11)
    at Function.forEach (D:\PATH_TO_MY_PROJECT\node_modules\lodash\lodash.js:9342:14)
    at D:\PATH_TO_MY_PROJECT\node_modules\copy-webpack-plugin\dist\index.js:184:30
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\PATH_TO_MY_PROJECT\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (D:\PATH_TO_MY_PROJECT\node_modules\tapable\lib\Hook.js:35:21)
    at asyncLib.forEach.err (D:\PATH_TO_MY_PROJECT\node_modules\webpack\lib\Compiler.js:355:27)
    at done (D:\PATH_TO_MY_PROJECT\node_modules\neo-async\async.js:2854:11)
    at D:\PATH_TO_MY_PROJECT\node_modules\neo-async\async.js:2805:7
    at D:\PATH_TO_MY_PROJECT\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by skipjack** [comment]
Yeah, I believe the latest version is only compatible with v3. I will work on fixing that soon. If you are in a rush, you can submit a PR to alter [this line](https://github.com/skipjack/directory-tree-webpack-plugin/blob/master/src/index.js#L27) which should now follow [this pattern](https://webpack.js.org/api/compiler-hooks/#hooks) and I'd be happy to ship a new release.

Also, I may be missing something but based on the stack trace it looks like your error is coming from the `copy-webpack-plugin` and not this one?

**Comment by ghost** [comment]
You are absolutely right. It's my fault about which plugin was a root cause. I am so sorry.

I wish I could help you with PR but I am beginner in this area. But I will see.

Many thanks for the response

**Comment by skipjack** [comment]
Just pushed a new release to remove the deprecation warning when used with webpack v4.

https://github.com/skipjack/directory-tree-webpack-plugin/blob/master/CHANGELOG.md

**Comment by LifeIsStrange** [comment]
@skipjack what about webpack 5? :)

**Comment by skipjack** [comment]
@LifeIsStrange try it out and let me know! You can create a new issue either way. If it works as is we can just update the peer dependency to allow v5. Otherwise we'll need to figure out what's broken and fix it before bumping the peer dependency.

**Comment by LifeIsStrange** [comment]
@skipjack thanks for the quick answer :)
Well my Vue setup (and Vue in general) is only compatible with webpack 4.x so I won't be able to test it but it's not an issue I was just curious about it for the future :)
